Before clicking Send Request,make sure you start the node process e.g node/nodemon server.js
Install `Rest Client` extension for Vs Code

###
POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
"firstname" : "Test", "lastname" : "Tester", "email": "test@mail.com", "password": "12345678"
}

###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
"email": "test@mail.com", "password": "12345678"
}

###
POST http://localhost:3000/api/v1/user/refresh
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWU2NmY3MTQ2NDZmODMyNTBiYzEyNmYiLCJpYXQiOjE2NDI2NjExMzEsImV4cCI6MTY0MjY2MTQzMX0.v22TieKOBJ149oEepJGcH-6OJg12TUgjjFgILQTfOmQ"
}

###
GET http://localhost:3000/api/v1/user/list
Content-Type: application/json

{

    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWU2NmY3MTQ2NDZmODMyNTBiYzEyNmYiLCJpYXQiOjE2NDI2NjE0MTgsImV4cCI6MTY0MjY2MTUzOH0.DyJpMhBtnAm1eIeWb1uje71_rnPKvoa2xyaVX50T7Rw"
}

###
GET http://localhost:3000/api/v1/user/logout
Content-Type: application/json

{
    "id" : ""
}
